### ISSUE TITLE
Skipping sending test report to cavy-cli - Network request failed.

### ISSUE THREAD

**Issue by sarthakmis** [pixielabs/cavy#127]
Test are getting passed but in the end I am getting this line 
**Skipping sending test report to cavy-cli - Network request failed.**

How to generate a test report here

**Comment by AbigailMcP** [comment]
Hey there @sarthakmis! This is actually expected behaviour.

By default, Cavy attempts to send a test report to cavy-cli by detecting whether the test server is running. If it's not, then it skips this step and outputs the message you're seeing here.

If you'd like to send a test report, then you need to install cavy-cli and run you're tests as per the instructions in the cavy-cli [README](https://github.com/pixielabs/cavy-cli). This can be particularly helpful for integrating your tests into a CI setup, for example.

Thanks for letting us know that this message was confusing though - I'm going to change it so that it's more informative 👌
