### ISSUE TITLE
What is the recommended way to separate cavy from production?

### ISSUE THREAD

**Issue by ethantran** [pixielabs/cavy#13]
I was thinking of doing 

```
render() {
let app = <App/>
if (__DEV__) {
app = <Tester><App/></Tester>
}
return app
}
```

```
class Button extends Component {}
if (__DEV__) {
Button = hook(Button)
}
```

The second one won't work since it needs props.generateTestHook, but in production won't generateTestHook be unnecessarily adding to store?

**Comment by AbigailMcP** [comment]
Thanks for the feedback @ethantran !
We don't have a concrete recommendation right now - potentially keep your app wrapped within the Tester component, but pass in an empty array instead of specs. Something like:

```
<Tester specs={this.state.runTests ? [AppSpec] : []} store={testHookStore}>
       <App />
</Tester>
```

It's definitely on the roadmap to improve this functionality (see issue #1) - pull requests are very welcome!

**Comment by ethantran** [comment]
Cool, I'll do that for now then.

**Comment by AbigailMcP** [comment]
Hey @ethantran - out of curiosity, it would be great to get an idea of how you're using Cavy / what you're using Cavy for!

If you have a moment, please drop me a quick message at abigail@pixielabs.io. Thanks!

**Comment by TGPSKI** [comment]
Here's my strategy: https://github.com/TGPSKI/cavy/blob/add-jenkins-reporting/sample-app/EmployeeDirectory/index.ios.js#L10

**Comment by lisbakke** [comment]
How are you guys separating Cavy testing from development on the commandline? It would be nice to run `npm start` for development and use the cavy CLI to run tests, but I haven't found a good way to do this so far.

**Comment by jalada** [comment]
@lisbakke there's not a _great_ way of doing it right now, you're right! We're looking to more tightly integrate Cavy and cavy-cli together so that this becomes the default behaviour. Stay tuned!

If you're interested; our current plan is to have Cavy ping the cavy-cli reporting server and only run tests if it's waiting for results. You're welcome to try that yourself; cavy-cli is a fairly simple codebase to muck around on.
