### ISSUE TITLE
React.createRef support

### ISSUE THREAD

**Issue by AlastairTaft** [pixielabs/cavy#133]
With newer versions of React, you'd use `React.createRef`, however this does not seem to be compatible with cavy. Do you guys plan on supporting it?

**Comment by AbigailMcP** [comment]
Hi @AlastairTaft - I'm not sure I understand the problem. Have you come across an issue using Cavy alongside `React.createRef`?

Cavy makes use of the alternative callback refs under the hood to store your testable components so that you can refer to them in your tests.

I'd need to have more of a think about it, but I'm not sure how we'd use the new `React.createRef`, or whether we actually need to (I was under the impression that callback refs will continue to be supported by React).

Let me know if you have any particular thoughts / ideas on the topic though!

**Comment by AlastairTaft** [comment]
Thanks for the reply. I'll admit I don't know much about how React works with refs internally, but with the `React.createRef` method it returns an object whereas cavy falls over when it tries to run this as if it were a function.

> I was under the impression that callback refs will continue to be supported by React
Ah, you're probably right, I'm not sure why, but I had trouble with the old ref way when upgrading my app to Expo v33. Probably my fault as I didn't dig to much into how refs worked. But unfortunately I ended up having to comment out all the cavy refs but I'd like to get them back up and running in the future.

**Comment by AbigailMcP** [comment]
@AlastairTaft - ah are you trying to pass in your own refs in addition to Cavy refs? If you post a code snippet here I'd be happy to investigate why things weren't working as expected 👍

**Comment by AlastairTaft** [comment]
I should of started with that. We're trying to do this after upgrading.

```
this.loginRef = React.createRef()
// ...
<Component
  ref={this.props.generateTestHook(LoginId.screen, this.loginRef)}
/>
```

**Comment by AbigailMcP** [comment]
I see, yes that is an issue! You're right, Cavy doesn't support your _own_ refs created via `React.createRef()` as an argument to `generateTestHook`. It expects your ref to be a callback function.

I don't have an immediate answer other than using a callback style ref, but I'll have a think about how we might be able to support this going forward.

Thanks for bring this to our attention!

**Comment by AlastairTaft** [comment]
Thank you!

**Comment by AbigailMcP** [comment]
Hi @AlastairTaft - we've just published a new version of Cavy that supports `React.createRef` (https://github.com/pixielabs/cavy/pull/139)

Hope this helps!

**Comment by AlastairTaft** [comment]
Thanks @AbigailMcP !
