### ISSUE TITLE
Support for ejected expo apps (Expokit)

### ISSUE THREAD

**Issue by Poeticode** [pixielabs/cavy#155]
So I know this wouldn't be high up in the priority queue since the RN team is deprecating Expokit, but do you guys think it's doable to get Cavy working with it?

**Comment by AbigailMcP** [comment]
Hi @Poeticode ! Thanks for your interest in Cavy.

Unfortunately, as you expected, we're not planning on looking into ways Cavy could support Expokit directly.

I don't have experience using Expokit, so can't really give you any specific advice on the integration, but if you can't build your app with `react-native run-[ios, android]`, then you won't be able to use Cavy CLI directly, since`cavy run-[ios, android]` runs these React Native CLI commands under the hood.

However, Cavy tests themselves will still work and run on app boot if the entry point specified returns your app wrapped in the `Tester` component i.e. looks like `index.test.js` in [these docs](https://cavy.app/docs/getting-started/setting-cavy-up). Test results will appear in the debugger console.

I'll leave this issue open in case other Cavy user have had experience with Expokit.

**Comment by AbigailMcP** [comment]
@jalada - please see above. Can you suggest anything else that might help?

**Comment by Poeticode** [comment]
Thanks for the info! Expokit has been the main source of just about every issue our team has been running into, so it's much more likely for us to recreate it as a bare-bones react-native app than to get Cavy working with Expokit, ha. But I'll let you know if we figure anything out before the conversion.

**Comment by AbigailMcP** [comment]
Ha! Makes sense. Yes, definitely keep us in the loop 👍

**Comment by AbigailMcP** [comment]
Hi @Poeticode ! I'm not sure how far you got with integrating Cavy, but if your issue is with running the tests via cavy-cli, then the latest update might help.

You can now build and run your app separately to Cavy (by whatever means you need to) and then run `cavy run-ios --skipbuild`.

This command starts the report server and listens for test results without first attempting to build your app via `react-native run-ios` under the hood.

**Comment by Poeticode** [comment]
Sorry that this is such a late response! We successfully converted our app to a barebones react-native app, and integrating cavy with it was a cinch. 

My apologies that I can't test for posterity whether the latest update supports Expokit. My team is otherwise very grateful for the tool you all have built, and will definitely push upstream any improvements/fixes we make.

**Comment by AbigailMcP** [comment]
Great news! I'm glad you got on well with the Cavy integration :) We always love to hear feedback / suggestions for improvements, so definitely let us know how you get on 🎉
