### ISSUE TITLE
Google SignIn Testing

### ISSUE THREAD

**Issue by thehellmaker** [pixielabs/cavy#168]
I have an app has login only using Google
Google SignIn opens a view where I do not have access to components to wrap with hooks. In such case how do you end up testing it with Cavy?

**Comment by jalada** [comment]
Hey @thehellmaker, what component/library are you using for Google SSO?

**Comment by thehellmaker** [comment]
I use this 

https://github.com/react-native-community/google-signin

**Comment by thehellmaker** [comment]
Since during signin it opens a view which is google signin.. How do I set up test hooks into google view to put email and password into it and submit...

**Comment by AbigailMcP** [comment]
Hey @thehellmaker ! Sorry it's been a while - were you able to make any progress with this?

It's going to be difficult for me to test this without seeing for myself how the component works in a real app. Would you be able to link me to a basic react native app with this google-signin implemented so I can see what we might be able to do?

**Comment by MrLoh** [comment]
I am also using google signing and I don't think this is in the scope of cavy, since cavy cannot interact with your app but only with your code, since you cannot complete the google signin without touching the screen you won't be able to do this with cavy. If you want to really test this a true E2E testing framework that can interact with web view contents like Appium is your only option (afaik not even detox can interact with web view content).

**Comment by jalada** [comment]
Thanks @MrLoh! Useful information. I'm going to close this for the time being as it sounds like this plugin has a native webview which Cavy can't get at. If that's incorrect, and there's something else going on, let us know and we'll reopen this.
