### ISSUE TITLE
Difference from appium tests

### ISSUE THREAD

**Issue by talarari** [pixielabs/cavy#17]
Could you please elaborate on how this is different from appium tests?
Thanks

**Comment by faceyspacey** [comment]
I haven't done the Appium tests but I always wondered how the names of selectors for elements in Appium reflects names and components in your actual app. How are you supposed to know the selector names? So at the very least this seems to let you provide names in your code, which makes them easily recallable in your tests. 

That said, rather than having to change my code, I really wish enzyme style selectors could be used in a real app somehow. Figuring that out--and perhaps that might take some work by the React and React Native teams--seems to the holy grail. Until then this is a very exciting solution.

**Comment by talarari** [comment]
You select components by accessibility id, so you need to provide that as a prop in your code.
But its not bad if you use proper sentences because​ then you also have a more accessible app.

**Comment by AbigailMcP** [comment]
@talarari - you're right, Cavy is definitely a comparable tool to Appium. The key difference is that (like you say) Appium uses native hooks to access components, whereas Cavy uses React Native refs.

This means Cavy sits _directly_ within your React Native environment (working identically with both Android and iOS builds), making it really quick and simple to integrate into your app.
