### ISSUE TITLE
Problem using redux form

### ISSUE THREAD

**Issue by FR98** [pixielabs/cavy#202]
It is possible to use cavy with redux form? I have a login form with this input redux Field

![Screenshot from 2020-09-19 13-33-11](https://user-images.githubusercontent.com/19533793/93687706-de425800-fa7c-11ea-8115-c6827552e290.png)

![Screenshot from 2020-09-19 13-33-31](https://user-images.githubusercontent.com/19533793/93687722-f619dc00-fa7c-11ea-80ee-ef904e62d61a.png)

And I am able to press buttons and move between screens, but when i try to fill the input field it doesnt work...

![Screenshot from 2020-09-19 13-36-42](https://user-images.githubusercontent.com/19533793/93687737-2e211f00-fa7d-11ea-9bba-8b26db93132f.png)

![Screenshot from 2020-09-19 13-37-00](https://user-images.githubusercontent.com/19533793/93687746-42fdb280-fa7d-11ea-9231-44c44320a1ae.png)

I think its because of the hook ref, but not sure. Does anyone has any idea or solution to this?

**Comment by AbigailMcP** [comment]
Hi @FR98 ! Have you tried adding the `generateTestHook` ref to the inner `<TextInput>` instead of the `<Field>` component? Cavy needs a reference to the component with the `onChangeText` prop for `fillIn` to work.

**Comment by FR98** [comment]
Hi @AbigailMcP , thanks for your response... I can't do that because I use the `<Field>` component in others input fields at the same time (username and password) so I cannot define the `generateTestHook` ref in the inner `<TextInput>`. So I tried through pass the ref but it doesn't work as I spected and then I tried to define the `generateTestHook` ref in the `<Field>` dynamicaly by passing the name but it doesnt work :( 

![Screenshot from 2020-09-29 23-10-45](https://user-images.githubusercontent.com/19533793/94645448-221d3480-02a9-11eb-9cc3-dea2f7bf42d7.png)

![Screenshot from 2020-09-29 23-10-27](https://user-images.githubusercontent.com/19533793/94645461-26e1e880-02a9-11eb-87eb-2f7a44112596.png)

![Screenshot from 2020-09-29 23-11-00](https://user-images.githubusercontent.com/19533793/94645473-2a756f80-02a9-11eb-959c-bd1ccd43b49f.png)

**Comment by AbigailMcP** [comment]
Ah I see! Sorry, I'm unfamiliar with how Redux Form works.

I've taken a closer look and think I have a solution - you're almost there!

In your form component:
```jsx
<Field name="email" cavyName='LoginScreen.Username' component={RenderInput} />
<Field name="name" cavyName='LoginScreen.Password' component={RenderInput} />
```
In your RenderInput component:

```jsx
export default function RenderInput({ input, cavyName }) {
  const generateTestHook = useCavy();
  const TestableTextInput = wrap(TextInput);

  return( 
    <TestableTextInput {...input} ref={generateTestHook(cavyName)}/>
  )
}
```

and in your tests:

```js
spec.it('Success Index', async function() {
  ...
  const username = await spec.findComponent('LoginScreen.Username');
  usernameInput.props.onChange('abigail');

  const password = await spec.findComponent('LoginScreen.Password');
  passwordInput.props.onChange('mypassword');
});
```

Running these tests with this code works for me :)

Compared to your solution, there were two things I needed to change to get this to work due to how Redux Form is rendering it's components:
1. Wrapping the input component (see [these docs](https://cavy.app/docs/getting-started/hooking-up-components#wrap-function)).
2. Not using `fillIn` - when I inspected the components returned in the test using `findComponent`, I could see that `onChangeText` was not included in its props (which is what `fillIn` uses under the hood). However, I saw that there was an `onChange` prop that I could call directly! (see [these docs](https://cavy.app/docs/api/test-helpers#findcomponentidentifier)).

**Comment by FR98** [comment]
Oh, it works! Thank you so much!
