### ISSUE TITLE
component.props.onChange' is undefined

### ISSUE THREAD

**Issue by Marzdor** [pixielabs/cavy#208]
Not sure if this is a bug or just a misunderstanding of how I think wrap() works.

I use this`@ptomasroos/react-native-multi-slider` for a slider component and I am trying to simulate an `onChange` event with a custom helper. Based on my understanding in order to access the props of the component it needs to be wrapped. 

Small example of how I think it should work
```
import React from 'react';
import MultiSlider from '@ptomasroos/react-native-multi-slider';
import {useCavy, wrap} from 'cavy';

const Duration = props => {
  const generateTestHook = useCavy();
  const TestableSlider = wrap(MultiSlider);

  return (
    <View>
      <TestableSlider
        ref={generateTestHook('SLIDER')}
        onValuesChange={values => props.handelFilters('duration', values)}
        // ... other props
      />
    </View>
  );
};

export default Duration;
```

However, with the above I get the warning `passing a class component into wrap` which is accurate since the slider is a class component.
Don't you need to warp components in order to access their props?

EDIT : realized it was `onValuesChange` and not `onChange` below can be ignored
After that warning I get a failed test with `component.props.onChange' is undefined` but the component has the `onChange` prop.

**Comment by Marzdor** [comment]
Realized I had a typo for my failed test onValuesChange and not onChange.

Also realized that I don't need to wrap the slider to access onValuesChange.

But, now I am wondering why it is necessary to wrap react-native components. I see this note in the documentation `(which is neither a React Class nor a Function Component)` but am trying to better understand how they are not a React Class.

For example `<View>` in the definition extends `ViewBase` which is a typeof ViewComponent that extends `React.Component<ViewProps>`

**Comment by AbigailMcP** [comment]
Glad you got it working accessing the `onValuesChange` prop!

Re your second question, there are two types of components you need to wrap in order to test it's props:

1. A function component (as explained in the docs)
2. Some of React Native's basic components like `<Text>` and `<TextInput>`. This is unfortunately due to React Native restructuring some of it's core components ([this blog post explains it well](https://medium.com/swlh/react-natives-re-architecture-in-2020-9bb82659792c)). In short, when you add a ref to these components, React Native are now forwarding it so that a Native component is returned and _not_ the React Native component itself. This means that the JS props are not for Cavy to call from within tests.

The current solution is to wrap these components so that Cavy can obtain a reference to these props. It's not ideal, but we're working on a solution at the moment that means you don't have to do this :)

**Comment by AbigailMcP** [comment]
Closing for now as I don't think there was an issue, but feel free to ask questions on here / continue the discussion.
