### ISSUE TITLE
Future of Cavy and Community

### ISSUE THREAD

**Issue by thehellmaker** [pixielabs/cavy#211]
Hi,
I have tried out detox and cavy for my project. Cavy is amazing as a project but one major concern i see is that the only committer to the project is abigail and rarely any other committer. Now i have to say abigail awesome commitment on singlehandedly building this entire framework. 

But the major problem I see here is 
1. If abigail leaves pixie labs or moves onto another project in pixie labs what will happen to cavy?
2. Is pixie labs investing in building a community around cavy?

**Comment by jalada** [comment]
Hi @thehellmaker, I'm head of engineering here at Pixie Labs. Thanks for your questions, and your praise of Cavy!

Rest assured, I take the responsibility for our open source projects seriously. The whole engineering team has, at some point, had a hand in working on Cavy and since we built it we've invested many hundreds of hours of company time on building and maintaining the library and its community, and I fully intend for us to continue that trend.
