### ISSUE TITLE
How to move component??

### ISSUE THREAD

**Issue by nguyencaochien** [pixielabs/cavy#32]
Can i automation moving or rotate component by this library?

**Comment by jalada** [comment]
@nguyencaochien that depends on the component in question. You may need to write your own spec helper function that calls the relevant `props` functions on the component in order to make it behave how you want it to.

See, for example, our implementation of [`press`](https://github.com/pixielabs/cavy/blob/master/src/TestScope.js#L150).

**Comment by jalada** [comment]
Closing this issue, but feel free to continue asking questions :)
