### ISSUE TITLE
Support for create-react-native-app / Expo

### ISSUE THREAD

**Issue by davetobin** [pixielabs/cavy#34]
Is there a way to tie in Cavy with `create-react-native-app` (https://facebook.github.io/react-native/docs/getting-started.html)? 

This doesn't seem to use the AppRegistry and I'm not sure how go about adding Cavy. Here are the files given by default:

![image](https://user-images.githubusercontent.com/6198085/26978863-d3cd046e-4d24-11e7-8a47-d65a6e8d8a75.png)

It would be good to be able to add Cavy and try it out at the most basic level and build from there.

EDIT: I see a similar issue to https://github.com/pixielabs/cavy/issues/23 when I add my own main.js
`undefined is not an object (evaluating '_this2.context.testHooks.add')`

**Comment by jalada** [comment]
Hi @davetobin! `create-react-native-app` uses [Expo](https://expo.io/) which is wrapping your app already. We've not tried Cavy with Expo yet, but I'll put it on the list so we can get back to you. If you make any headway in the mean time please let us know!

**Comment by mandx** [comment]
As a workaround, I'm hooking up Cavy right in the main `App.js` file. Instead of exporting as `default` the `App` component, my default export is the `AppWrapper` component in the examples. What the CRNA entrypoint does is call `AppRegistry.registerComponent` with the default export of the root `App.js` file.

**Comment by donnes** [comment]
Hello @mandx can you provide an example about this workaround?
Other question, you're using `CRNA` or `expo init`?

Thanks!

**Comment by mandx** [comment]
@donnes I'm sorry, I don't have access to that code anymore; my previous comment is from a bit more than a year ago, and I don't have access to that code anymore. And not even I can make sense of that comment right now, apparently Cavy has changed quite a bit since then, so I'm not sure if it still applies...

**Comment by donnes** [comment]
@mandx Ohh, ok you're right!
Thanks!
