### ISSUE TITLE
Is it possible to use Jest with Cavy?

### ISSUE THREAD

**Issue by lisbakke** [pixielabs/cavy#70]
Sorry if this is a dumb question -- I haven't used Cavy or Jest, only read through the docs.

Jest's ability to take snapshots and compare them seems powerful.

Is it possible to do that within Cavy tests? Would it be possible to write a Cavy test that navigates to a specific screen, grabs some JSX tree, then uses Jest to compare it to a snapshot?

**Comment by jalada** [comment]
@lisbakke Cavy is primarily designed to do end-to-end or black-box style testing. That means it should really only assert expectations via observation, rather than grabbing underlying information about what's going on in the app.

e.g. instead of comparing a JSX tree to a snapshot, you should look for the presence of a rendered thing. It's not the greatest of distinctions; I guess it's more about best practices than anything.

From a technical point of view grabbing the rendered JSX tree from outside of React (Native) is tricky. That's why we have the whole test hook system. Jest (and co.) solve that by doing fake rendering so they can keep track of what the tree looks like.

**Comment by jalada** [comment]
I'm going to close this issue as it's just a question, but feel free to continue discussion and I'll re-open it if there's anything we need to do :)
