### ISSUE TITLE
make a ref to non component

### ISSUE THREAD

**Issue by lamaabdulla** [pixielabs/cavy#93]
Hello, 

I have this piece of code o a method in javaScript : 

      Alert.alert(
                        '    ',
                        '     ',
                        [
                          { text: 'OK', onPress: () => Actions.pop({ refresh: { key: Math.random } }) },
                        ],
                        { cancelable: false }
                    );

and I want to hook up the OK button, is there any way to do that ! 

thanks a lot.

**Comment by AbigailMcP** [comment]
Hey @lamaabdulla, thanks for getting in touch.

Unfortunately, since `Alert` is native, this is tricky to achieve with Cavy (which just deals with JS).

Have you tried spinning out your `onPress` into a separate function and calling this from within your Cavy test? Worth a shot!

Let me know how you get on with that.

**Comment by jalada** [comment]
Closing this for now, feel free to comment if you need more assistance @lamaabdulla :)
